- id: '1619552687242'
  alias: Clock Brightness
  description: ''
  trigger:
  - platform: state
    entity_id: input_number.clock_brightness
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: esp32/output/brightness
      payload: '{{ states.input_number.clock_brightness.state }}'
  mode: single
- id: '1638132276419'
  alias: Flight entry notification
  trigger:
  - platform: event
    event_type: opensky_entry
  action:
  - service: notify.mobile_app_sm_g986u
    data:
      message: Flight entry of {{ trigger.event.data.callsign }}, Altitude {{ trigger.event.data.altitude
        }} meters.
