- id: '1619552687242'
  alias: Clock Brightness
  description: ''
  trigger:
  - platform: state
    entity_id: input_number.clock_brightness
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: esp32/output/brightness
      payload: '{{ states.input_number.clock_brightness.state }}'
  mode: single
- id: '1638132276419'
  alias: Flight entry notification
  trigger:
  - platform: event
    event_type: opensky_entry
  action:
  - service: notify.mobile_app_sm_g986u
    data:
      message: Flight entry of {{ trigger.event.data.callsign }}, Altitude {{ trigger.event.data.altitude
        }} meters.
- id: '1641250283772'
  alias: Volume Slider Change Bedroom
  description: ''
  trigger:
  - platform: state
    entity_id: input_number.livingroom_gc_volume_slider
  condition: []
  action:
  - service: rest_command.set_livingroom_gc_volume
  mode: single
- id: '1641250553089'
  alias: Volume Change Livingroom GC
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.livingroom_gc_volume
  condition: []
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.livingroom_gc_volume_slider
      value: '{{ states.sensor.bedroom_volume_slider.state }}'
  mode: single
- id: '1644438643517'
  alias: OwnTone-Switch To Group
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.owntone_output_living_room_gh
  - platform: state
    entity_id: media_player.owntone_output_bedroom_speaker
  condition:
  - condition: state
    entity_id: media_player.owntone_output_living_room_gh
    state: 'on'
  - condition: state
    entity_id: media_player.owntone_output_bedroom_speaker
    state: 'on'
  action:
  - service: media_player.turn_on
    data: {}
    target:
      entity_id: media_player.owntone_output_home_group
  mode: single
- id: '1646450453527'
  alias: Eufy - Display image on TV
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.doorbell_ringing_sensor
    to: 'True'
    from: 'False'
  condition: []
  action:
  - service: camera.snapshot
    data:
      filename: /config/www/images/doorbell.png
    target:
      device_id: 5bf9fd8da629f452bccc126bad2e538d
  - service: notify.android_tv_fire_tv
    data:
      title: Front Doorbell
      data:
        position: top-right
        image:
          path: /config/www/images/doorbell.png
      message: Doorbell
  mode: single
- id: '1647999023211'
  alias: Watchtower
  description: ''
  trigger:
  - platform: webhook
    webhook_id: 21582bf2-7327-45e7-9a0b-04a33d7c43d2-8dd5245e-42a8-4e15-9884-b3bade86ecce
  condition: []
  action:
  - service: input_text.set_value
    data:
      value: '{{ trigger.data }}'
    target:
      entity_id: input_text.watchtower
  mode: single
