- id: '1619552687242'
  alias: Clock Brightness
  description: ''
  trigger:
  - platform: state
    entity_id: input_number.clock_brightness
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: esp32/output/brightness
      payload: '{{ states.input_number.clock_brightness.state }}'
  mode: single
- id: '1638132276419'
  alias: Flight entry notification
  trigger:
  - platform: event
    event_type: opensky_entry
  action:
  - service: notify.mobile_app_sm_g986u
    data:
      message: Flight entry of {{ trigger.event.data.callsign }}, Altitude {{ trigger.event.data.altitude
        }} meters.
- id: '1641250283772'
  alias: Volume Slider Change Bedroom
  description: ''
  trigger:
  - platform: state
    entity_id: input_number.livingroom_gc_volume_slider
  condition: []
  action:
  - service: rest_command.set_livingroom_gc_volume
  mode: single
- id: '1641250553089'
  alias: Volume Change Livingroom GC
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.livingroom_gc_volume
  condition: []
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.livingroom_gc_volume_slider
      value: '{{ states.sensor.bedroom_volume_slider.state }}'
  mode: single
- id: '1644438643517'
  alias: OwnTone-Switch To Group
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.owntone_output_living_room_gh
  - platform: state
    entity_id: media_player.owntone_output_bedroom_speaker
  condition:
  - condition: state
    entity_id: media_player.owntone_output_living_room_gh
    state: 'on'
  - condition: state
    entity_id: media_player.owntone_output_bedroom_speaker
    state: 'on'
  action:
  - service: media_player.turn_on
    data: {}
    target:
      entity_id: media_player.owntone_output_home_group
  mode: single
- id: '1646450453527'
  alias: Eufy - Display image on TV
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.doorbell_ringing_sensor
    to: 'True'
    from: 'False'
  condition: []
  action:
  - service: camera.snapshot
    data:
      filename: /config/www/images/doorbell.png
    target:
      device_id: 5bf9fd8da629f452bccc126bad2e538d
  - service: notify.android_tv_fire_tv
    data:
      title: Front Doorbell
      data:
        position: top-right
        image:
          path: /config/www/images/doorbell.png
      message: Doorbell
  mode: single
- id: '1647999023211'
  alias: Watchtower
  description: ''
  trigger:
  - platform: webhook
    webhook_id: 21582bf2-7327-45e7-9a0b-04a33d7c43d2-8dd5245e-42a8-4e15-9884-b3bade86ecce
    allowed_methods:
    - POST
    - PUT
    local_only: true
  condition: []
  action:
  - service: input_text.set_value
    data:
      value: '{{ trigger.data }}'
    target:
      entity_id: input_text.watchtower
  mode: single
- id: '1649894408085'
  alias: UPS Power Outage
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.apc_nut_status_data
    from:
    - OL
    - OL CHRG
    to:
    - OB DISCHRG
    - OL DISCHRG
  condition: []
  action:
  - service: notify.mobile_app_sm_g986u
    data:
      message: Power failure detected
      title: POWER OUTAGE
  mode: single
- id: '1671396670067'
  alias: Uptime Robot Announcement
  description: ''
  trigger:
  - platform: event
    event_type: call-service
    event_data:
      domain: notify
      service: mobile_app_sm_g986u
      service_data:
        title: Uptime Kuma
        data:
          status: 0
  condition: []
  action: []
  mode: single
- id: '1673390530487'
  alias: Eufy - Motion Detect
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.doorbell_motion_detected
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_sm_g986u
    data:
      message: Motion Detected by HA
      title: Eufy
  mode: single
- id: '1676045424188'
  alias: Notification - FedEx Package Notification
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.mail_fedex_delivered
    above: 0
  condition: []
  action:
  - condition: numeric_state
    entity_id: sensor.mail_fedex_delivered
    above: -0.6
  - service: notify.mobile_app_sm_g986u
    data:
      message: Looks like Fedex delivered your package. {{ states.sensor.mail_fedex_delivered.state
        }} / {{ states.sensor.mail_fedex_packages.state }} packages delivered.
      title: Fedex Delivery
  mode: single
- id: '1682546505858'
  alias: restart 'rtlamr2mqtt' When Locked
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.gas_meter
    to:
    for:
      hours: 3
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: hassio.addon_restart
    data:
      addon: 6713e36e_rtlamr2mqtt
    enabled: true
  - service: notify.mobile_app_sm_g986u
    data:
      message: Restarting 'rtlamr2mqtt'
  mode: single
- id: '1687703076206'
  alias: Mets game start
  description: ''
  trigger:
  - platform: template
    value_template: '{{ as_timestamp(states.sensor.mets_tracker.attributes.date) -
      as_timestamp(now()) < 600 }}'
  condition:
  - condition: state
    entity_id: media_player.sony_bravia_tv
    state: 'on'
  action:
  - service: notify.pushbullet
    data:
      message: '{{ states.sensor.mets_tracker.attributes.team_name }} vs {{states.sensor.mets_tracker.attributes.opponent_name
        }} game starts in 10 minutes'
  - service: notify.google_assistant_sdk
    data:
      message: '{{ states.sensor.mets_tracker.attributes.team_name }} vs {{     states.sensor.mets_tracker.attributes.opponent_name
        }} starts in 10 minutes.'
  mode: single
- id: '1704686826560'
  alias: Reolink Doorbell Alert
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.reolink_video_doorbell_visitor
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_sm_g986u
    data:
      message: command_launch_app
      data:
        package_name: com.mcu.reolink
        Activity Class: com.android.bc.login.WelcomeActivity
        Action: android.intent.action.VIEW
        Data URI: S.UID=95270006IZGX19BB
  mode: single
- id: '1706914699046'
  alias: Reolink Doorbell Activated
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.reolink_video_doorbell_visitor
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.google_assistant_sdk
    data:
      message: Someone is at the door
  - service: remote.turn_on
    target:
      entity_id: remote.living_room_tv
    data:
      activity: ipcam://
  mode: single
- id: '1709079489328'
  alias: Fire Tablet Charge On
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.fire_tablet_battery_level
    below: 8
  condition: []
  action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.fire_tablet_power_relay
  mode: single
- id: '1709079616905'
  alias: Fire Tablet Charger Off
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.fire_tablet_battery_level
    above: 95
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id:
      - switch.fire_tablet_power_relay
    data: {}
  mode: single
- id: '1713374933093'
  alias: Water Leak Alert
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.washing_machine_leak_sensor_water
    - binary_sensor.water_heater_leak_sensor_water
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition: []
  action:
  - service: notify.wayne_phone_sms
    data:
      message: 'ALERT: {{ trigger.to_state.name }} triggered'
  mode: single
- id: '1715651530621'
  alias: Wawa Regular Gas Price
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.wawa_regular_gas
    to:
  condition: []
  action:
  - service: input_number.set_value
    metadata: {}
    data:
      value: '{{states(''input_number.wawa_regular_gas_current_value'')|float}}'
    target:
      entity_id: input_number.wawa_regular_gas_prev_value
  - service: input_number.set_value
    metadata: {}
    data:
      value: '{{states(''sensor.wawa_regular_gas'')|float}}'
    target:
      entity_id: input_number.wawa_regular_gas_current_value
  mode: single
- id: '1715712048622'
  alias: Frigate - Car Detection - Front
  description: ''
  trigger:
  - platform: mqtt
    topic: frigate/events
  condition:
  - condition: and
    conditions:
    - condition: template
      value_template: '{{ trigger.payload_json[''after''][''camera''] == ''frigate_front''
        }}'
    - condition: template
      value_template: '{{ trigger.payload_json[''after''][''label''] == ''car'' }}'
    - condition: template
      value_template: '{{ trigger.payload_json[''after''][''stationary''] == false
        }}'
  action:
  - service: downloader.download_file
    data:
      overwrite: true
      filename: snapshot_car_front.jpg
      url: https://wld1014.duckdns.org:8123/api/frigate/notifications/{{trigger.payload_json['after']['id']}}/thumbnail.jpg
  mode: single
- id: '1715719165497'
  alias: Frigate - Car Detection - Doorbell
  description: ''
  trigger:
  - platform: mqtt
    topic: frigate/events
  condition:
  - condition: and
    conditions:
    - condition: template
      value_template: '{{ trigger.payload_json[''after''][''camera''] == ''frigate_doorbell''
        }}'
    - condition: template
      value_template: '{{ trigger.payload_json[''after''][''label''] == ''car'' }}'
    - condition: template
      value_template: '{{ trigger.payload_json[''after''][''stationary''] == false
        }}'
  action:
  - service: downloader.download_file
    data:
      overwrite: true
      filename: snapshot_car_doorbell.jpg
      url: https://wld1014.duckdns.org:8123/api/frigate/notifications/{{trigger.payload_json['after']['id']}}/thumbnail.jpg
  mode: single
- id: '1715719508935'
  alias: Frigate - Person Detection - Front
  description: ''
  trigger:
  - platform: mqtt
    topic: frigate/events
  condition:
  - condition: and
    conditions:
    - condition: template
      value_template: '{{ trigger.payload_json[''after''][''camera''] == ''frigate_front''
        }}'
    - condition: template
      value_template: '{{ trigger.payload_json[''after''][''label''] == ''person''
        }}'
    - condition: template
      value_template: '{{ trigger.payload_json[''after''][''stationary''] == false
        }}'
  action:
  - service: downloader.download_file
    data:
      overwrite: true
      filename: snapshot_person_front.jpg
      url: https://wld1014.duckdns.org:8123/api/frigate/notifications/{{trigger.payload_json['after']['id']}}/thumbnail.jpg
  mode: single
- id: '1715740885115'
  alias: QuickCheck Regular Gas Price
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.quickcheck_regular_gas
    to:
  condition: []
  action:
  - service: input_number.set_value
    metadata: {}
    data:
      value: '{{states(''input_number.quickcheck_regular_gas_current_value'')|float}}'
    target:
      entity_id: input_number.quickcheck_regular_gas_prev_value
  - service: input_number.set_value
    metadata: {}
    data:
      value: '{{states(''sensor.quickcheck_regular_gas'')|float}}'
    target:
      entity_id: input_number.quickcheck_regular_gas_current_value
  mode: single
- id: '1720545368078'
  alias: Doorbell check for unavailable
  description: ''
  trigger:
  - platform: state
    entity_id:
    - camera.frigate_doorbell
    to: unavailable
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_sm_g986u
    metadata: {}
    data:
      message: Doorbell needs to be rebooted.
      title: Alert
  mode: single
- id: '1722782659480'
  alias: Set LR fan to 0% when off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - fan.lr_fan
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 1
  condition: []
  action:
  - service: fan.set_percentage
    target:
      entity_id: fan.lr_fan
    data:
      percentage: 0
  mode: single
- id: '1723049264354'
  alias: House Shutdown with Fan DoubleTap
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 247c05371f40491555b315759db17a2d
    type: action
    subtype: down_double
  condition: []
  action:
  - service: input_button.press
    metadata: {}
    data: {}
    target:
      entity_id: input_button.house_shutdown_button
  mode: single
