
#  Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
#    base_url: https://192.168.0.238:8123

opnsense:
  url: https://opnsense.localdomain/api
  api_secret: !secret opnsense_api_secret
  api_key: !secret opnsense_api_key
  verify_ssl: false
  
# https Setup
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
 
# Example configuration.yaml entry
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  # "Project ID" in the Device Access Console
  project_id: !secret nest_project_id
  # Provide the full path exactly as shown under "Subscription name" in Google Cloud Console
  subscriber_id: !secret nest_subscriber_id
  
homeassistant:
  packages: !include_dir_named packages
  customize: !include customize.yaml

sensor: !include_dir_merge_list conf/sensor/
template: !include_dir_merge_list conf/template/
rest: !include_dir_merge_list conf/rest/
switch: !include_dir_merge_list conf/switch/
rest_command: !include_dir_merge_named conf/rest_command/
fan: !include_dir_merge_list conf/fan/
# scrape: !include_dir_merge_list conf/scrape
multiscrape: !include_dir_merge_list conf/multiscrape

mqtt:
  sensor: !include_dir_merge_list conf/mqtt/

#shell_command:
#  owntone_sonos_on: 'curl -X PUT "http://192.168.0.249:3689/api/outputs/79880900644729" --data "{\"selected\":true, \"volume\": 10}"'
#  owntone_tv_on: 'curl -X PUT "http://192.168.0.249:3689/api/outputs/4021710331606" --data "{\"selected\":true, \"volume\": 10}"'
#  owntone_sonos_off: 'curl -X PUT "http://192.168.0.249:3689/api/outputs/79880900644729" --data "{\"selected\":false, \"volume\": 10}"'
#  owntone_tv_off: 'curl -X PUT "http://192.168.0.249:3689/api/outputs/4021710331606" --data "{\"selected\":false, \"volume\": 10}"'
#  owntone_google_home_livingroom_on: 'curl -X PUT "http://192.168.0.249:3689/api/outputs/2544647392" --data "{\"selected\":true, \"volume\": 20}"'
#  owntone_google_home_livingroom_off: 'curl -X PUT "http://192.168.0.249:3689/api/outputs/2544647392" --data "{\"selected\":false, \"volume\": 48}"'

#  - platform: weatheralerts
#    state: NJ
#    zone: 12
#    county: 23
  
logbook:
  exclude:
    entities:
      - sensor.date
      - sensor.time
      - sensor.date_time
      - sensor.time_date
      - sensor.date_time_iso
      - sensor.internet_time
      - sensor.time_utc

recorder:
  db_url: !secret recorder_db_url

  commit_interval: 1
  purge_keep_days: 64
  exclude:
    entities:
      - sensor.date
      - sensor.time
      - sensor.date_time
      - sensor.time_date
      - sensor.date_time_iso
      - sensor.internet_time
      - sensor.time_utc

logger:
  default: info

influxdb:
  api_version: 2
  ssl: false
  host: 192.168.200.3
  port: 8086
  token: !secret influxdb_token
  organization: ha
  bucket: home_assistant
  tags:
    source: HA
  tags_attributes:
    - friendly_name
  default_measurement: units
  exclude:
    entities:
      - zone.home
    domains:
      - persistent_notification
      - person
  include:
    domains:
      - sensor
      - binary_sensor
      - sun
    entities:
      - weather.kldj_daynight

geo_location:
  - platform: usgs_earthquakes_feed
    feed_type: "past_month_all_earthquakes"
    radius: 75
