- platform: template
  switches:
    sonos_daap:
      value_template: "{{ is_state('input_boolean.sonos_daap', 'on') }}"
      turn_on:
        - service: input_boolean.turn_on
          entity_id: input_boolean.sonos_daap
        - service: script.daap_sonos_livingroom_on
      turn_off:
        - service: input_boolean.turn_off
          entity_id: input_boolean.sonos_daap
        - service: script.daap_sonos_livingroom_off
