- platform: history_stats
  name: heat_on_time_last_month
  entity_id: sensor.hvac_status
  state: ['heating_on', 'heat_cool_heating_on']
  type: time
  start: "{{ (as_timestamp(now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0)) - ((states['sensor.days_in_month'].state | int) *24*3600)) }}"
  end: "{{ as_timestamp(now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0)) }}"

- platform: history_stats
  name: heat_on_duty_cycle_last_month
  entity_id: sensor.hvac_status
  state: ['heating_on', 'heat_cool_heating_on']
  type: ratio
  start: "{{ (as_timestamp(now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0)) - ((states['sensor.days_in_month'].state | int) *24*3600)) }}"
  end: "{{ as_timestamp(now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0)) }}"

- platform: history_stats
  name: heat_on_count_last_month
  entity_id: sensor.hvac_status
  state: ['heating_on', 'heat_cool_heating_on']
  type: count
  start: "{{ (as_timestamp(now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0)) - ((states['sensor.days_in_month'].state | int) *24*3600)) }}"
  end: "{{ as_timestamp(now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0)) }}"

- platform: history_stats
  name: cool_on_time_last_month
  entity_id: sensor.hvac_status
  state: ['cooling_on', 'heat_cool_cooling_on']
  type: time
  start: "{{ (as_timestamp(now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0)) - ((states['sensor.days_in_month'].state | int) *24*3600)) }}"
  end: "{{ as_timestamp(now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0)) }}"

- platform: history_stats
  name: cool_on_duty_cycle_last_month
  entity_id: sensor.hvac_status
  state: ['cooling_on', 'heat_cool_cooling_on']
  type: ratio
  start: "{{ (as_timestamp(now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0)) - ((states['sensor.days_in_month'].state | int) *24*3600)) }}"
  end: "{{ as_timestamp(now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0)) }}"

- platform: history_stats
  name: cool_on_count_last_month
  entity_id: sensor.hvac_status
  state: ['cooling_on', 'heat_cool_cooling_on']
  type: count
  start: "{{ (as_timestamp(now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0)) - ((states['sensor.days_in_month'].state | int) *24*3600)) }}"
  end: "{{ as_timestamp(now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0)) }}"
  