- platform: history_stats
  name: heat_on_time_this_month
  entity_id: sensor.hvac_status
  state: ['heating_on', 'heat_cool_heating_on']
  type: time
  start: '{{ now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: heat_on_duty_cycle_this_month
  entity_id: sensor.hvac_status
  state: ['heating_on', 'heat_cool_heating_on']
  type: ratio
  start: '{{ now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: heat_on_count_this_month
  entity_id: sensor.hvac_status
  state: ['heating_on', 'heat_cool_heating_on']
  type: count
  start: '{{ now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: cool_on_time_this_month
  entity_id: sensor.hvac_status
  state: ['cooling_on', 'heat_cool_cooling_on']
  type: time
  start: '{{ now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: cool_on_duty_cycle_this_month
  entity_id: sensor.hvac_status
  state: ['cooling_on', 'heat_cool_cooling_on']
  type: ratio
  start: '{{ now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: cool_on_count_this_month
  entity_id: sensor.hvac_status
  state: ['cooling_on', 'heat_cool_cooling_on']
  type: count
  start: '{{ now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
