- platform: mqtt
  name: 'shinobi_ups_BatteryVoltage'
  state_topic: '/shinobi/x728'
  unit_of_measurement: 'V'
  value_template: '{{ value_json.BatteryVoltage | round(1) }}'

- platform: mqtt
  name: 'shinobi_ups_BatteryCapacity'
  state_topic: '/shinobi/x728'
  unit_of_measurement: '%'
  value_template: '{{ value_json.BatteryCapacity }}'
  
- platform: mqtt
  name: 'Shinobi UPS Status'
  state_topic: '/shinobi/x728'
  unit_of_measurement: 'Source'
  value_template: '{{ value_json.UPS_Status }}'
  icon: mdi:power-plug

- platform: mqtt
  name: 'shinobi_cpu_temperature'
  state_topic: '/shinobi/cpu'
  unit_of_measurement: '°F'
  value_template: '{{ value_json.cpu_temperature }}'

- platform: mqtt
  name: 'shinobi_cpu_load'
  state_topic: '/shinobi/cpu'
  unit_of_measurement: '%'
  value_template: '{{ value_json.cpu_load }}'
  