- platform: systemmonitor
  resources:
    - type: processor_use
    - type: memory_free
    - type: throughput_network_in
      arg: eth0
    - type: throughput_network_out
      arg: eth0
    - type: last_boot
    