- platform: template
  sensors:
# Used for dashboard display
    livingroom_fan_mode:
      friendly_name: 'Living Room Fan Mode'
      value_template: >-
        {% if states['fan.in_wall_smart_fan_control'].attributes.speed == "off" %}
          Off
        {% elif states['fan.in_wall_smart_fan_control'].attributes.speed == "low" %}
          Low
        {% elif states['fan.in_wall_smart_fan_control'].attributes.speed == "medium" %}
          Medium
        {% elif states['fan.in_wall_smart_fan_control'].attributes.speed == "high" %}
          High
        {% endif %}

# Used for dashboard display
    bedroom_fan_mode:
      friendly_name: 'Bedroom Fan Mode'
      value_template: >-
        {% if states['fan.bedroom_fan_current_value'].attributes.speed == "off" %}
          Off
        {% elif states['fan.bedroom_fan_current_value'].attributes.speed == "low" %}
          Low
        {% elif states['fan.bedroom_fan_current_value'].attributes.speed == "medium" %}
          Medium
        {% elif states['fan.bedroom_fan_current_value'].attributes.speed == "high" %}
          High
        {% endif %}

    hvac_status:
      friendly_name: 'HVAC Status'
      value_template: >-
        {% if is_state("climate.thermostat", "off") %}
          off
        {% elif is_state("climate.living_room", "heat") and states['climate.living_room'].attributes.hvac_action == "off" %}
          heating_off
        {% elif is_state("climate.living_room", "heat") and states['climate.living_room'].attributes.hvac_action == "heating" %}
          heating_on
        {% elif is_state("climate.living_room", "cool") and states['climate.living_room'].attributes.hvac_action == "off" %}
          cooling_off
        {% elif is_state("climate.living_room", "cool") and states['climate.living_room'].attributes.hvac_action == "cooling" %}
          cooling_on
        {% elif is_state("climate.living_room", "heat_cool") and states['climate.living_room'].attributes.hvac_action == "off" %}
          heat_cool_off
        {% elif is_state("climate.living_room", "heat_cool") and states['climate.living_room'].attributes.hvac_action == "heating" %}
          heat_cool_heating_on
        {% elif is_state("climate.living_room", "heat_cool") and states['climate.living_room'].attributes.hvac_action == "cooling" %}
          heat_cool_cooling_on
        {% endif %}

    temp_average:
      friendly_name: 'Temp Average'
      unit_of_measurement: '°F'
      value_template: '{{ states.sensor.living_room_temperature.state | round(1) }}'
      
    outside_temp:
      friendly_name: 'Outside Temperature'
      unit_of_measurement: '°F'
      value_template: '{{ states["weather.kewr_daynight"].attributes.temperature }}'
      
    uptime_ha:
      friendly_name: Uptime HA
      icon_template: mdi:server
      value_template: >-
        {% set lb = states('sensor.last_boot') %}
        {% if lb != 'unknown' %}
          {% set seconds = (as_timestamp(now()) - as_timestamp(lb))|int %}
          {% set days = (seconds / 86400)|int %}
          {% set seconds = seconds % 86400 %}
          {% set hours = (seconds / 3600)|int %}
          {% set seconds = seconds % 3600 %}
          {% set minutes = (seconds / 60)|int %}
          {% set seconds = seconds % 60 %}
          {% if hours == 0 and minutes == 0 %}
            {{ time }} seconds
          {% else %}
            {%- if days > 0 -%}
              {%- if days == 1 -%}
                1 day
              {%- else -%}
                {{ days }} days
              {%- endif -%}
            {%- endif -%}
            {%- if hours > 0 and days < 7 -%}
              {%- if days > 0 -%}
                {{ ', ' }}
              {%- endif -%}
              {%- if hours == 1 -%}
                1 hour
              {%- else -%}
                {{ hours }} hours
              {%- endif -%}
            {%- endif -%}
            {%- if days == 0 and minutes > 0 -%}
              {%- if hours > 0 -%}
                {{ ', ' }}{{ minutes }} min
              {%- else -%}
                {%- if minutes == 1 -%}
                  1 minute
                {%- else -%}
                  {{ minutes }} minutes
                {%- endif -%}
              {%- endif -%}
            {%- endif -%}
          {% endif %}
        {% else %}
          unknown
        {% endif %}

    cool_kwh_yesterday:
      friendly_name: 'Cool kWh Yesterday'
      unit_of_measurement: 'kWh'
      value_template: "{{ '%.2f' | format(states.sensor.cool_on_time_yesterday.state | float * 3.228) }}"

    cool_kwh_thisweek:
      friendly_name: 'Cool kWh This Week'
      unit_of_measurement: 'kWh'
      value_template: "{{ '%.2f' | format(states.sensor.cool_on_time_thisweek.state | float * 3.228) }}"

    cool_kwh_lastweek:
      friendly_name: 'Cool kWh Last Week'
      unit_of_measurement: 'kWh'
      value_template: "{{ '%.2f' | format(states.sensor.cool_on_time_lastweek.state | float * 3.228) }}"

    cool_kwh_this_month:
      friendly_name: 'Cool kWh This Month'
      unit_of_measurement: 'kWh'
      value_template: "{{ '%.2f' | format(states.sensor.cool_on_time_this_month.state | float * 3.228) }}"

    cool_kwh_last_month:
      friendly_name: 'Cool kWh last Month'
      unit_of_measurement: 'kWh'
      value_template: "{{ '%.2f' | format(states.sensor.cool_on_time_last_month.state | float * 3.228) }}"

    days_in_month:
      friendly_name: 'Days In Month'
      value_template: >-
        {% if now().month in [1,2,4,6,8,9,11] %}
          31
        {% elif now().month in [5,7,10,12] %}
          30
        {% elif now().month == 3 and ((now().year-2000) % 4 > 0) %}
          28
        {% elif now().month == 3 and ((now().year-2000) % 4 == 0) %}
          29
        {% endif %}
        
    sonos_playing:
      friendly_name: 'Sonos playing'
      value_template: >-
        {%- if is_state("media_player.sonos_arc_2", "playing") %}
          <h3>{{states.media_player.sonos_arc_2.attributes.media_title}}</h3><p>{{states.media_player.sonos_arc_2.attributes.media_artist}}<br />{{states.media_player.sonos_arc_2.attributes.media_album_name}}</p>
        {% else %}
          Not playing
        {%- endif %}
  