- platform: template
  fans:
    living_room_fan:
      unique_id: living_room_fan
      friendly_name: "Living Room Fan"
      value_template: >
        {{ states('fan.in_wall_fan_speed_control_500s') }}
      preset_mode_template: >
        {%- set v = state_attr('fan.in_wall_fan_speed_control_500s', 'percentage') | int(0) -%}
        {%- set vals = { 0: 'off', 33: 'low', 67: 'medium', 100: 'high' } -%}
        {{ vals[v] }}
      turn_on:
        service: fan.turn_on
        target:
          entity_id: fan.in_wall_fan_speed_control_500s
      turn_off:
        service: fan.turn_off
        target:
          entity_id: fan.in_wall_fan_speed_control_500s
      set_preset_mode:
        service: fan.set_percentage
        data:
          percentage: >
            {%- set vals = { 'off': 0, 'low': 33, 'medium': 67, 'high': 100 } -%}
            {{ vals[preset_mode]}}
        target:
          entity_id: fan.in_wall_fan_speed_control_500s
      speed_count: 3
      preset_modes:
        - "off"
        - "low"
        - "medium"
        - "high"
